version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-dhparam:/etc/nginx/dhparam
      - nginx-certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - bridge
      - nginx

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - nginx-certs:/etc/nginx/certs:rw
      - nginx-acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - bridge

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    volumes:
      - portainer
      - /var/run/docker.sock:/var/run/docker.sock
    networks: nginx
    environment:
      LETSENCRYPT_HOST: portainer.hubspace.de
      VIRTUAL_HOST: portainer.hubspace.de
      VIRTUAL_PORT: 9000

volumes:
  nginx-conf:
  nginx-vhost:
  nginx-html:
  nginx-dhparam:
  nginx-certs:
  nginx-acme:
  portainer:

networks:
  nginx:
    external: false
